let p=15;
let t=12;
let r=12;
let SI=(p*t*r);
document.getElementById("id1").innerText=SI;
const colors=["Blue", "Black", " Red", "Yellow", "green"];
document.getElementById("id2").innerText=colors.toString();
colors.pop();
document.getElementById("id3").innerHTML=colors;
colors.push("Orange");
document.getElementById("id4").innerHTML=colors;
colors.shift();
document.getElementById("id5").innerHTML=colors;
colors.unshift("White");
document.getElementById("id6").innerHTML=colors;
const animals=["cat", "rat", "dog", "elephant", "horse"];
document.getElementById("id7").innerHTML=animals;
animals.splice(3,0,"rabbit");
document.getElementById("id8").innerHTML=animals;
animals.splice(2,2,"goat","monkey","camel");
document.getElementById("id9").innerHTML=animals;